<?php

namespace Database\Seeders;

use App\Models\Equipement;
use App\Models\EquipementHistorique;
use App\Models\User;
use Illuminate\Database\Seeder;

class EquipementSeeder extends Seeder
{
    public function run(): void
    {
        // Récupérer les utilisateurs par département
        $aissatou = User::where('email', 'a.mbaye@senstock.sn')->first();   // Comptabilité
        $cheikh   = User::where('email', 'c.gueye@senstock.sn')->first();   // Logistique
        $rokhaya  = User::where('email', 'r.diop@senstock.sn')->first();    // RH
        $modou    = User::where('email', 'm.fall@senstock.sn')->first();    // Commercial
        $ndeye    = User::where('email', 'n.sarr@senstock.sn')->first();    // Direction
        $mamadou  = User::where('email', 'responsable-it@senstock.sn')->first(); // DSI
        $ibrahima = User::where('email', 'i.sow@senstock.sn')->first();     // DSI technicien
        $fatou    = User::where('email', 'f.ndiaye@senstock.sn')->first();  // DSI technicien
        $admin    = User::where('email', 'admin@senstock.sn')->first();

        $equipements = [

            // ─── ORDINATEURS PORTABLES ───────────────────────────────────────

            [
                'nom'                  => 'Laptop Direction Générale',
                'categorie'            => 'ordinateur_portable',
                'marque'               => 'Dell',
                'modele'               => 'Latitude 5530',
                'numero_serie'         => 'DL-SN-2023-001',
                'adresse_mac'          => 'A4:C3:F0:12:34:56',
                'adresse_ip'           => '192.168.1.10',
                'assigned_user_id'     => $ndeye?->id,
                'localisation'         => 'Bureau Direction — Bât. A',
                'departement'          => 'Direction',
                'statut'               => 'actif',
                'date_achat'           => '2023-03-15',
                'prix_achat'           => 950000,
                'fournisseur'          => 'XELLTEKK',
                'numero_bon_commande'  => 'BC-2023-0042',
                'fin_garantie'         => '2026-03-15',
                'specifications'       => ['cpu' => 'Intel Core i7-1255U', 'ram' => '16 Go DDR5', 'stockage' => '512 Go SSD NVMe', 'os' => 'Windows 11 Pro'],
                'notes'                => 'Réservé à la Directrice Générale. Chiffrement BitLocker activé.',
                'created_by'           => $admin?->id,
            ],
            [
                'nom'                  => 'Laptop Comptabilité 1',
                'categorie'            => 'ordinateur_portable',
                'marque'               => 'HP',
                'modele'               => 'EliteBook 840 G9',
                'numero_serie'         => 'HP-SN-2022-011',
                'adresse_mac'          => 'B8:D9:4C:23:45:67',
                'adresse_ip'           => '192.168.1.21',
                'assigned_user_id'     => $aissatou?->id,
                'localisation'         => 'Bureau Comptabilité — Bât. B, Étage 1',
                'departement'          => 'Comptabilité',
                'statut'               => 'actif',
                'date_achat'           => '2022-06-10',
                'prix_achat'           => 780000,
                'fournisseur'          => 'XELLTEKK',
                'numero_bon_commande'  => 'BC-2022-0078',
                'fin_garantie'         => '2025-06-10',
                'specifications'       => ['cpu' => 'Intel Core i5-1235U', 'ram' => '8 Go DDR4', 'stockage' => '256 Go SSD', 'os' => 'Windows 11 Pro'],
                'notes'                => 'Logiciel Sage Comptabilité installé.',
                'created_by'           => $admin?->id,
            ],
            [
                'nom'                  => 'Laptop RH',
                'categorie'            => 'ordinateur_portable',
                'marque'               => 'Lenovo',
                'modele'               => 'ThinkPad E15 Gen 4',
                'numero_serie'         => 'LN-SN-2023-007',
                'adresse_mac'          => 'C2:E1:7A:34:56:78',
                'adresse_ip'           => '192.168.1.31',
                'assigned_user_id'     => $rokhaya?->id,
                'localisation'         => 'Bureau RH — Bât. A, RDC',
                'departement'          => 'Ressources Humaines',
                'statut'               => 'actif',
                'date_achat'           => '2023-01-20',
                'prix_achat'           => 720000,
                'fournisseur'          => 'XELLTEKK',
                'numero_bon_commande'  => 'BC-2023-0015',
                'fin_garantie'         => '2026-01-20',
                'specifications'       => ['cpu' => 'AMD Ryzen 5 5625U', 'ram' => '8 Go DDR4', 'stockage' => '512 Go SSD', 'os' => 'Windows 11 Pro'],
                'created_by'           => $admin?->id,
            ],
            [
                'nom'                  => 'Laptop Commercial',
                'categorie'            => 'ordinateur_portable',
                'marque'               => 'Dell',
                'modele'               => 'Vostro 5510',
                'numero_serie'         => 'DL-SN-2022-019',
                'adresse_mac'          => 'D4:F2:8B:45:67:89',
                'adresse_ip'           => '192.168.1.41',
                'assigned_user_id'     => $modou?->id,
                'localisation'         => 'Bureau Commercial — Bât. B, RDC',
                'departement'          => 'Commercial',
                'statut'               => 'actif',
                'date_achat'           => '2022-09-05',
                'prix_achat'           => 650000,
                'fournisseur'          => 'Informatique Plus Dakar',
                'numero_bon_commande'  => 'BC-2022-0103',
                'fin_garantie'         => '2025-09-05',
                'specifications'       => ['cpu' => 'Intel Core i5-11320H', 'ram' => '8 Go DDR4', 'stockage' => '256 Go SSD', 'os' => 'Windows 10 Pro'],
                'notes'                => 'Garantie expirée en septembre 2025. À renouveler.',
                'created_by'           => $admin?->id,
            ],
            [
                'nom'                  => 'Laptop DSI — Responsable IT',
                'categorie'            => 'ordinateur_portable',
                'marque'               => 'Dell',
                'modele'               => 'Precision 5570',
                'numero_serie'         => 'DL-SN-2023-003',
                'adresse_mac'          => 'E6:A4:1D:56:78:90',
                'adresse_ip'           => '192.168.1.5',
                'assigned_user_id'     => $mamadou?->id,
                'localisation'         => 'Salle DSI — Bât. A, Étage 2',
                'departement'          => 'DSI',
                'statut'               => 'actif',
                'date_achat'           => '2023-02-01',
                'prix_achat'           => 1250000,
                'fournisseur'          => 'XELLTEKK',
                'numero_bon_commande'  => 'BC-2023-0008',
                'fin_garantie'         => '2026-02-01',
                'specifications'       => ['cpu' => 'Intel Core i9-12900H', 'ram' => '32 Go DDR5', 'stockage' => '1 To SSD NVMe', 'os' => 'Ubuntu 22.04 LTS / Windows 11 Pro'],
                'notes'                => 'Station de travail haute performance pour administration réseau.',
                'created_by'           => $admin?->id,
            ],

            // ─── ORDINATEURS DE BUREAU ────────────────────────────────────────

            [
                'nom'                  => 'Poste Bureau Logistique 1',
                'categorie'            => 'ordinateur_bureau',
                'marque'               => 'HP',
                'modele'               => 'ProDesk 400 G9',
                'numero_serie'         => 'HP-DK-2021-031',
                'adresse_mac'          => 'F8:75:E6:67:89:AB',
                'adresse_ip'           => '192.168.2.11',
                'assigned_user_id'     => $cheikh?->id,
                'localisation'         => 'Entrepôt Logistique — Bât. C',
                'departement'          => 'Logistique',
                'statut'               => 'actif',
                'date_achat'           => '2021-11-15',
                'prix_achat'           => 480000,
                'fournisseur'          => 'XELLTEKK',
                'numero_bon_commande'  => 'BC-2021-0156',
                'fin_garantie'         => '2024-11-15',
                'specifications'       => ['cpu' => 'Intel Core i5-10500', 'ram' => '8 Go DDR4', 'stockage' => '500 Go HDD', 'os' => 'Windows 10 Pro'],
                'notes'                => 'Garantie expirée. Prévoir remplacement disque dur — lecture lente signalée.',
                'created_by'           => $admin?->id,
            ],
            [
                'nom'                  => 'Poste Bureau Accueil',
                'categorie'            => 'ordinateur_bureau',
                'marque'               => 'Lenovo',
                'modele'               => 'IdeaCentre 3',
                'numero_serie'         => 'LN-DK-2022-044',
                'adresse_ip'           => '192.168.2.20',
                'localisation'         => 'Accueil principal — Bât. A, RDC',
                'departement'          => 'Administration',
                'statut'               => 'actif',
                'date_achat'           => '2022-04-18',
                'prix_achat'           => 380000,
                'fournisseur'          => 'Informatique Plus Dakar',
                'fin_garantie'         => '2025-04-18',
                'specifications'       => ['cpu' => 'Intel Core i3-10100', 'ram' => '4 Go DDR4', 'stockage' => '1 To HDD', 'os' => 'Windows 10 Home'],
                'notes'                => 'Poste partagé. Logiciels: Chrome, Outlook, imprimante réseau configurée.',
                'created_by'           => $admin?->id,
            ],
            [
                'nom'                  => 'Poste Salle de Réunion',
                'categorie'            => 'ordinateur_bureau',
                'marque'               => 'Dell',
                'modele'               => 'OptiPlex 3000',
                'numero_serie'         => 'DL-DK-2023-052',
                'adresse_ip'           => '192.168.2.30',
                'localisation'         => 'Salle de réunion principale — Bât. A, Étage 1',
                'departement'          => 'Direction',
                'statut'               => 'actif',
                'date_achat'           => '2023-07-10',
                'prix_achat'           => 420000,
                'fournisseur'          => 'XELLTEKK',
                'numero_bon_commande'  => 'BC-2023-0089',
                'fin_garantie'         => '2026-07-10',
                'specifications'       => ['cpu' => 'Intel Core i5-12500', 'ram' => '8 Go DDR4', 'stockage' => '256 Go SSD', 'os' => 'Windows 11 Pro'],
                'notes'                => 'Connecté au vidéoprojecteur et à l\'écran de présentation.',
                'created_by'           => $admin?->id,
            ],
            [
                'nom'                  => 'Poste Bureau DSI — Technicien 1',
                'categorie'            => 'ordinateur_bureau',
                'marque'               => 'HP',
                'modele'               => 'EliteDesk 800 G6',
                'numero_serie'         => 'HP-DK-2022-060',
                'adresse_ip'           => '192.168.1.6',
                'assigned_user_id'     => $ibrahima?->id,
                'localisation'         => 'Salle DSI — Bât. A, Étage 2',
                'departement'          => 'DSI',
                'statut'               => 'actif',
                'date_achat'           => '2022-08-22',
                'prix_achat'           => 520000,
                'fournisseur'          => 'XELLTEKK',
                'fin_garantie'         => '2025-08-22',
                'specifications'       => ['cpu' => 'Intel Core i7-10700', 'ram' => '16 Go DDR4', 'stockage' => '512 Go SSD', 'os' => 'Windows 11 Pro'],
                'created_by'           => $admin?->id,
            ],

            // ─── SERVEURS ────────────────────────────────────────────────────

            [
                'nom'                  => 'Serveur Principal SENSTOCK',
                'categorie'            => 'serveur',
                'marque'               => 'Dell',
                'modele'               => 'PowerEdge R740',
                'numero_serie'         => 'DL-SRV-2020-001',
                'adresse_mac'          => '00:1A:2B:3C:4D:5E',
                'adresse_ip'           => '192.168.1.1',
                'localisation'         => 'Salle serveurs — Bât. A, Sous-sol',
                'departement'          => 'DSI',
                'statut'               => 'actif',
                'date_achat'           => '2020-05-20',
                'prix_achat'           => 5800000,
                'fournisseur'          => 'XELLTEKK',
                'numero_bon_commande'  => 'BC-2020-0012',
                'fin_garantie'         => '2025-05-20',
                'specifications'       => ['cpu' => '2x Intel Xeon Silver 4210R', 'ram' => '128 Go DDR4 ECC', 'stockage' => '4x 1.8 To SAS RAID 10', 'os' => 'Windows Server 2022 Standard'],
                'notes'                => 'Serveur de fichiers, Active Directory et applications métier. Sauvegarde quotidienne à 2h00. Contrat de maintenance Dell ProSupport.',
                'created_by'           => $admin?->id,
            ],
            [
                'nom'                  => 'Serveur de Sauvegarde NAS',
                'categorie'            => 'serveur',
                'marque'               => 'Synology',
                'modele'               => 'DiskStation DS1522+',
                'numero_serie'         => 'SY-NAS-2022-001',
                'adresse_mac'          => '00:11:32:AA:BB:CC',
                'adresse_ip'           => '192.168.1.2',
                'localisation'         => 'Salle serveurs — Bât. A, Sous-sol',
                'departement'          => 'DSI',
                'statut'               => 'actif',
                'date_achat'           => '2022-01-15',
                'prix_achat'           => 2100000,
                'fournisseur'          => 'XELLTEKK',
                'numero_bon_commande'  => 'BC-2022-0003',
                'fin_garantie'         => '2027-01-15',
                'specifications'       => ['cpu' => 'AMD Ryzen V1500B', 'ram' => '16 Go DDR4 ECC', 'stockage' => '5x 4 To Seagate IronWolf (RAID 6)', 'os' => 'Synology DSM 7.2'],
                'notes'                => 'NAS dédié aux sauvegardes automatiques. Réplication vers cloud Synology C2 activée.',
                'created_by'           => $admin?->id,
            ],
            [
                'nom'                  => 'Serveur Web / Intranet',
                'categorie'            => 'serveur',
                'marque'               => 'HP',
                'modele'               => 'ProLiant DL360 Gen10',
                'numero_serie'         => 'HP-SRV-2021-002',
                'adresse_ip'           => '192.168.1.3',
                'localisation'         => 'Salle serveurs — Bât. A, Sous-sol',
                'departement'          => 'DSI',
                'statut'               => 'actif',
                'date_achat'           => '2021-08-10',
                'prix_achat'           => 3200000,
                'fournisseur'          => 'XELLTEKK',
                'fin_garantie'         => '2024-08-10',
                'specifications'       => ['cpu' => 'Intel Xeon Silver 4208', 'ram' => '32 Go DDR4 ECC', 'stockage' => '2x 480 Go SSD RAID 1', 'os' => 'Ubuntu Server 22.04 LTS'],
                'notes'                => 'Héberge l\'intranet SENSTOCK, la plateforme ITSM et les applications internes. Garantie expirée — surveiller.',
                'created_by'           => $admin?->id,
            ],

            // ─── IMPRIMANTES ─────────────────────────────────────────────────

            [
                'nom'                  => 'Imprimante Réseau — Comptabilité',
                'categorie'            => 'imprimante',
                'marque'               => 'HP',
                'modele'               => 'LaserJet Pro MFP M428fdw',
                'numero_serie'         => 'HP-IMP-2022-001',
                'adresse_mac'          => '3C:D9:2B:78:90:AB',
                'adresse_ip'           => '192.168.3.10',
                'localisation'         => 'Couloir Comptabilité — Bât. B, Étage 1',
                'departement'          => 'Comptabilité',
                'statut'               => 'actif',
                'date_achat'           => '2022-03-01',
                'prix_achat'           => 320000,
                'fournisseur'          => 'Bureau Services Dakar',
                'fin_garantie'         => '2025-03-01',
                'notes'                => 'Imprimante multifonction (impression, scan, copie, fax). Partagée par Comptabilité et RH. Toner changé en octobre 2024.',
                'created_by'           => $admin?->id,
            ],
            [
                'nom'                  => 'Imprimante Réseau — Direction',
                'categorie'            => 'imprimante',
                'marque'               => 'Canon',
                'modele'               => 'imageRUNNER ADVANCE C3525i',
                'numero_serie'         => 'CN-IMP-2021-002',
                'adresse_mac'          => '4E:F0:3A:89:AB:CD',
                'adresse_ip'           => '192.168.3.20',
                'localisation'         => 'Secrétariat Direction — Bât. A, RDC',
                'departement'          => 'Direction',
                'statut'               => 'actif',
                'date_achat'           => '2021-06-20',
                'prix_achat'           => 1850000,
                'fournisseur'          => 'Canon Sénégal',
                'fin_garantie'         => '2024-06-20',
                'notes'                => 'Copieur couleur haute capacité. Contrat de maintenance Canon — technicien Canon intervient trimestriellement.',
                'created_by'           => $admin?->id,
            ],
            [
                'nom'                  => 'Imprimante Logistique — Étiquettes',
                'categorie'            => 'imprimante',
                'marque'               => 'Zebra',
                'modele'               => 'ZT411',
                'numero_serie'         => 'ZB-IMP-2023-001',
                'adresse_ip'           => '192.168.3.30',
                'assigned_user_id'     => $cheikh?->id,
                'localisation'         => 'Entrepôt — Bât. C, Zone Expédition',
                'departement'          => 'Logistique',
                'statut'               => 'actif',
                'date_achat'           => '2023-04-05',
                'prix_achat'           => 580000,
                'fournisseur'          => 'XELLTEKK',
                'numero_bon_commande'  => 'BC-2023-0055',
                'fin_garantie'         => '2026-04-05',
                'notes'                => 'Imprimante d\'étiquettes thermiques pour les colis et stocks. Rouleaux d\'étiquettes 100x150mm.',
                'created_by'           => $admin?->id,
            ],

            // ─── RÉSEAU / SWITCHES ────────────────────────────────────────────

            [
                'nom'                  => 'Switch Principal — Cœur de réseau',
                'categorie'            => 'switch',
                'marque'               => 'Cisco',
                'modele'               => 'Catalyst 2960X-48FPS-L',
                'numero_serie'         => 'CS-SW-2020-001',
                'adresse_mac'          => '00:1C:5E:AA:BB:CC',
                'adresse_ip'           => '192.168.0.2',
                'localisation'         => 'Salle serveurs — Bât. A, Sous-sol',
                'departement'          => 'DSI',
                'statut'               => 'actif',
                'date_achat'           => '2020-05-20',
                'prix_achat'           => 1450000,
                'fournisseur'          => 'XELLTEKK',
                'numero_bon_commande'  => 'BC-2020-0013',
                'fin_garantie'         => '2025-05-20',
                'notes'                => '48 ports PoE+. Alimente les téléphones IP et les bornes WiFi. VLAN configurés : Data (10), VoIP (20), Management (99).',
                'created_by'           => $admin?->id,
            ],
            [
                'nom'                  => 'Switch Étage 1 — Bât. B',
                'categorie'            => 'switch',
                'marque'               => 'Cisco',
                'modele'               => 'SG350-28P',
                'numero_serie'         => 'CS-SW-2021-002',
                'adresse_ip'           => '192.168.0.3',
                'localisation'         => 'Baie réseau — Bât. B, Étage 1',
                'departement'          => 'DSI',
                'statut'               => 'actif',
                'date_achat'           => '2021-03-10',
                'prix_achat'           => 480000,
                'fournisseur'          => 'XELLTEKK',
                'fin_garantie'         => '2026-03-10',
                'notes'                => '28 ports dont 24 PoE. Dessert Comptabilité, RH et salles de réunion.',
                'created_by'           => $admin?->id,
            ],

            // ─── ROUTEUR ────────────────────────────────────────────────────

            [
                'nom'                  => 'Routeur Principal / Firewall',
                'categorie'            => 'routeur',
                'marque'               => 'Fortinet',
                'modele'               => 'FortiGate 60F',
                'numero_serie'         => 'FG-RT-2022-001',
                'adresse_ip'           => '192.168.0.1',
                'localisation'         => 'Salle serveurs — Bât. A, Sous-sol',
                'departement'          => 'DSI',
                'statut'               => 'actif',
                'date_achat'           => '2022-02-14',
                'prix_achat'           => 2200000,
                'fournisseur'          => 'XELLTEKK',
                'numero_bon_commande'  => 'BC-2022-0010',
                'fin_garantie'         => '2025-02-14',
                'specifications'       => ['os' => 'FortiOS 7.4.x'],
                'notes'                => 'Firewall UTM. Abonnement FortiGuard actif jusqu\'en février 2025. Règles IPS, filtrage web et VPN SSL configurés.',
                'created_by'           => $admin?->id,
            ],

            // ─── ONDULEUR ────────────────────────────────────────────────────

            [
                'nom'                  => 'Onduleur Salle Serveurs',
                'categorie'            => 'onduleur',
                'marque'               => 'APC',
                'modele'               => 'Smart-UPS 3000VA LCD',
                'numero_serie'         => 'APC-UPS-2020-001',
                'localisation'         => 'Salle serveurs — Bât. A, Sous-sol',
                'departement'          => 'DSI',
                'statut'               => 'actif',
                'date_achat'           => '2020-05-20',
                'prix_achat'           => 980000,
                'fournisseur'          => 'XELLTEKK',
                'numero_bon_commande'  => 'BC-2020-0014',
                'fin_garantie'         => '2023-05-20',
                'notes'                => 'Batteries remplacées en mars 2024. Autonomie estimée à 25 minutes sous charge complète. Monitoring via NMC installé.',
                'created_by'           => $admin?->id,
            ],
            [
                'nom'                  => 'Onduleur Bureau Direction',
                'categorie'            => 'onduleur',
                'marque'               => 'APC',
                'modele'               => 'Back-UPS 1200VA',
                'numero_serie'         => 'APC-UPS-2022-002',
                'localisation'         => 'Bureau Direction — Bât. A',
                'departement'          => 'Direction',
                'statut'               => 'actif',
                'date_achat'           => '2022-09-01',
                'prix_achat'           => 185000,
                'fournisseur'          => 'Électro Dakar',
                'fin_garantie'         => '2024-09-01',
                'notes'                => 'Alimente le laptop et l\'écran de la Direction.',
                'created_by'           => $admin?->id,
            ],

            // ─── OBJETS IoT ──────────────────────────────────────────────────

            [
                'nom'                  => 'Borne WiFi — Hall Accueil',
                'categorie'            => 'iot',
                'marque'               => 'Ubiquiti',
                'modele'               => 'UniFi AP U6 Pro',
                'numero_serie'         => 'UB-AP-2022-001',
                'adresse_mac'          => '78:45:58:12:AB:01',
                'adresse_ip'           => '192.168.0.21',
                'localisation'         => 'Hall Accueil — Bât. A, RDC',
                'departement'          => 'DSI',
                'statut'               => 'actif',
                'date_achat'           => '2022-06-01',
                'prix_achat'           => 195000,
                'fournisseur'          => 'XELLTEKK',
                'fin_garantie'         => '2027-06-01',
                'notes'                => 'WiFi 6. SSID : SENSTOCK-CORP (WPA3) et SENSTOCK-GUEST (portail captif). Géré par UniFi Controller.',
                'created_by'           => $admin?->id,
            ],
            [
                'nom'                  => 'Borne WiFi — Salle de réunion',
                'categorie'            => 'iot',
                'marque'               => 'Ubiquiti',
                'modele'               => 'UniFi AP U6 Lite',
                'numero_serie'         => 'UB-AP-2022-002',
                'adresse_mac'          => '78:45:58:12:AB:02',
                'adresse_ip'           => '192.168.0.22',
                'localisation'         => 'Salle de réunion — Bât. A, Étage 1',
                'departement'          => 'DSI',
                'statut'               => 'actif',
                'date_achat'           => '2022-06-01',
                'prix_achat'           => 125000,
                'fournisseur'          => 'XELLTEKK',
                'fin_garantie'         => '2027-06-01',
                'created_by'           => $admin?->id,
            ],
            [
                'nom'                  => 'Caméra IP — Entrée principale',
                'categorie'            => 'iot',
                'marque'               => 'Hikvision',
                'modele'               => 'DS-2CD2143G2-I',
                'numero_serie'         => 'HK-CAM-2022-001',
                'adresse_ip'           => '192.168.4.11',
                'localisation'         => 'Entrée principale — Bât. A, Extérieur',
                'departement'          => 'DSI',
                'statut'               => 'actif',
                'date_achat'           => '2022-07-15',
                'prix_achat'           => 145000,
                'fournisseur'          => 'XELLTEKK',
                'fin_garantie'         => '2025-07-15',
                'notes'                => 'Caméra 4MP, vision nocturne IR 40m. Enregistrement sur NVR Hikvision.',
                'created_by'           => $admin?->id,
            ],

            // ─── EN MAINTENANCE / HORS SERVICE ───────────────────────────────

            [
                'nom'                  => 'Laptop HP Ancien — Logistique',
                'categorie'            => 'ordinateur_portable',
                'marque'               => 'HP',
                'modele'               => 'ProBook 450 G5',
                'numero_serie'         => 'HP-SN-2019-005',
                'localisation'         => 'Stock DSI — Bât. A, Sous-sol',
                'departement'          => 'Logistique',
                'statut'               => 'en_maintenance',
                'date_achat'           => '2019-03-10',
                'prix_achat'           => 550000,
                'fournisseur'          => 'Informatique Plus Dakar',
                'fin_garantie'         => '2022-03-10',
                'specifications'       => ['cpu' => 'Intel Core i5-8250U', 'ram' => '8 Go DDR4', 'stockage' => '256 Go SSD', 'os' => 'Windows 10 Pro'],
                'notes'                => 'Remplacement de la batterie en cours. Charnière écran à réparer. Ticket #TCK ouvert.',
                'created_by'           => $admin?->id,
            ],
            [
                'nom'                  => 'Imprimante Ancienne — Hors service',
                'categorie'            => 'imprimante',
                'marque'               => 'Epson',
                'modele'               => 'WorkForce Pro WF-4745',
                'numero_serie'         => 'EP-IMP-2018-003',
                'localisation'         => 'Stock DSI — Bât. A, Sous-sol',
                'departement'          => 'Administration',
                'statut'               => 'hors_service',
                'date_achat'           => '2018-11-20',
                'prix_achat'           => 280000,
                'fournisseur'          => 'Bureau Services Dakar',
                'fin_garantie'         => '2020-11-20',
                'notes'                => 'Tête d\'impression hors service. Réparation non rentable — coût > valeur résiduelle. À déclasser.',
                'created_by'           => $admin?->id,
            ],
            [
                'nom'                  => 'Téléphone IP — Comptabilité',
                'categorie'            => 'telephone_ip',
                'marque'               => 'Yealink',
                'modele'               => 'T43U',
                'numero_serie'         => 'YL-TEL-2021-011',
                'adresse_mac'          => 'AA:BB:CC:11:22:33',
                'adresse_ip'           => '192.168.20.21',
                'assigned_user_id'     => $aissatou?->id,
                'localisation'         => 'Bureau Comptabilité — Bât. B, Étage 1',
                'departement'          => 'Comptabilité',
                'statut'               => 'actif',
                'date_achat'           => '2021-09-01',
                'prix_achat'           => 85000,
                'fournisseur'          => 'XELLTEKK',
                'fin_garantie'         => '2024-09-01',
                'notes'                => 'Extension SIP 2021. IPBX Asterisk configuré.',
                'created_by'           => $admin?->id,
            ],
        ];

        foreach ($equipements as $data) {
            $eq = Equipement::create($data);

            // Entrée d'historique initiale
            EquipementHistorique::create([
                'equipement_id'  => $eq->id,
                'user_id'        => $admin?->id,
                'type_mouvement' => 'autre',
                'nouvelle_valeur'=> 'Ajouté au parc',
                'commentaire'    => 'Intégration dans l\'inventaire SENSTOCK',
                'created_at'     => $eq->date_achat ?? now()->subMonths(rand(3, 24)),
            ]);

            // Si affecté, ajouter un mouvement d'affectation
            if ($eq->assigned_user_id) {
                EquipementHistorique::create([
                    'equipement_id'  => $eq->id,
                    'user_id'        => $admin?->id,
                    'type_mouvement' => 'affectation',
                    'nouvelle_valeur'=> $eq->assignedUser?->name,
                    'commentaire'    => 'Affectation initiale',
                    'created_at'     => now()->subMonths(rand(1, 12)),
                ]);
            }

            // Si en maintenance, ajouter un mouvement
            if ($eq->statut === 'en_maintenance') {
                EquipementHistorique::create([
                    'equipement_id'  => $eq->id,
                    'user_id'        => $ibrahima?->id,
                    'type_mouvement' => 'maintenance',
                    'ancienne_valeur'=> 'actif',
                    'nouvelle_valeur'=> 'en_maintenance',
                    'commentaire'    => 'Prise en charge pour réparation',
                    'created_at'     => now()->subDays(rand(3, 15)),
                ]);
            }
        }

        $this->command->info('✅ ' . count($equipements) . ' équipements ajoutés au parc informatique.');
    }
}
